name: Build IPQ807x NSS WiFi

on: workflow_dispatch

jobs:
    build:
        name: Prepare and build IPQ807x NSS generic images
        runs-on: ubuntu-latest

        steps:
        
            - name: Free Disk Space (Ubuntu)
              uses: jlumbroso/free-disk-space@main
              with:
                # this might remove tools that are actually needed,
                # if set to "true" but frees about 6 GB
                tool-cache: true
        
                # all of these default to true, but feel free to set to
                # "false" if necessary for your workflow
                android: false
                dotnet: false
                haskell: true
                large-packages: true
                swap-storage: true
                
            - name: Checkout
              uses: actions/checkout@v4
              
            - name: Disk space
              run: |
                   echo "Free space:"
                   df -h

            - name: Initialization environment
              env:
                DEBIAN_FRONTEND: noninteractive
              run: |
                sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
                sudo -E apt-get -qq update
                sudo -E apt-get -qq full-upgrade
                sudo -E apt-get -qq install ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache clang cmake cpio curl device-tree-compiler flex gawk gettext gcc-multilib g++-multilib git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libfuse-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses-dev libncurses-dev libpython3-dev libreadline-dev libssl-dev libtool llvm lrzsz genisoimage msmtp ninja-build p7zip p7zip-full patch pkgconf python3 python3-pyelftools python3-setuptools qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev
                sudo -E apt-get -qq autoremove --purge
                sudo -E apt-get -qq clean
                sudo timedatectl set-timezone "$TZ"
        
            - name: Update and install feeds
              run: |
                ./scripts/feeds update -a
                ./scripts/feeds install -a
                sh ./diy.sh
                
            - name: Import full config for IPQ807x NSS Generic
              run: |
                mv .full_config .config

            - name: QoL fixes on default config
              run: |
                mkdir -p files/etc/uci-defaults
                cat > files/etc/uci-defaults/99-qol_fixes << EOF
                uci set wireless.radio0.country='US'
                uci set wireless.radio1.country='US'
                uci set wireless.radio2.country='US'
                uci set wireless.radio1.disabled=0
                uci set wireless.radio2.disabled=0
                uci set pbuf.opt.memory_profile=auto
                uci set network.globals.packet_steering=0
                uci set firewall.@defaults[0].flow_offloading=0
                uci set ecm.@general[0].enable_bridge_filtering=0
                uci set system.@system[0].cronloglevel='7'
                /etc/init.d/mwan3 stop
                /etc/init.d/mwan3 disable
                /etc/init.d/sqm stop
                /etc/init.d/sqm disable
                uci commit
                EOF

            - name: Download package sources
              run: make download V=s

            - name: Build tools
              run: |
                make tools/install -j$(nproc) V=s || \
                make tools/install V=s

            - name: Build toolchain
              run: |
                make toolchain/install -j$(nproc) V=s || \
                make toolchain/install V=s

            - name: Build target images
              run: |
                make -j$(nproc) V=s || \
                make V=s

            - name: Get the current date
              run: echo "NOW=$(date +%F-%H%M)" >> $GITHUB_ENV

            - name: Create a release
              uses: "ncipollo/release-action@v1"
              with:
                name: "Updated prebuilt images (NSS-WiFi) ${{ env.NOW }}"
                commit: "main_nss"
                tag: "ipq807x-nsswifi-${{ env.NOW }}"
                generateReleaseNotes: true
                makeLatest: true
                artifacts: bin/targets/qualcommax/ipq807x/*
                token: "${{ secrets.GITHUB_TOKEN }}"
